/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: AllPrimitivesMessage.h
  Source: D:\Work\FastCycloneDdsCsharpBindings\src\CycloneDDS.Schema\TestData\Generated\AllPrimitivesMessage.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_ALLPRIMITIVESMESSAGE_H
#define DDSC_ALLPRIMITIVESMESSAGE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CycloneDDS_Schema_TestData_AllPrimitivesMessage
{
  int32_t Id;
  bool BoolField;
  uint8_t ByteField;
  int16_t Int16Field;
  int32_t Int32Field;
  int64_t Int64Field;
  float FloatField;
  double DoubleField;
  char * StringField;
} CycloneDDS_Schema_TestData_AllPrimitivesMessage;

extern const dds_topic_descriptor_t CycloneDDS_Schema_TestData_AllPrimitivesMessage_desc;

#define CycloneDDS_Schema_TestData_AllPrimitivesMessage__alloc() \
((CycloneDDS_Schema_TestData_AllPrimitivesMessage*) dds_alloc (sizeof (CycloneDDS_Schema_TestData_AllPrimitivesMessage)));

#define CycloneDDS_Schema_TestData_AllPrimitivesMessage_free(d,o) \
dds_sample_free ((d), &CycloneDDS_Schema_TestData_AllPrimitivesMessage_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ALLPRIMITIVESMESSAGE_H */
