namespace CycloneDDS.Schema
{
    using System;

    /// <summary>
    /// Internal attribute automatically generated by the code generator.
    /// Records which IDL file a type was generated into.
    /// Used for cross-assembly dependency resolution.
    /// </summary>
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
    public sealed class DdsIdlMappingAttribute : Attribute
    {
        /// <summary>
        /// The full C# name of the type.
        /// </summary>
        public string TypeFullName { get; }
        
        /// <summary>
        /// The IDL file where the type is defined (without extension).
        /// </summary>
        public string IdlFileName { get; }
        
        /// <summary>
        /// The IDL module path where the type is defined.
        /// </summary>
        public string IdlModule { get; }
        
        /// <summary>
        /// Initializes a new instance of the DdsIdlMappingAttribute class.
        /// </summary>
        /// <param name="typeName">Full C# type name.</param>
        /// <param name="idlFile">IDL file name.</param>
        /// <param name="idlModule">IDL module path.</param>
        public DdsIdlMappingAttribute(string typeName, string idlFile, string idlModule)
        {
            TypeFullName = typeName;
            IdlFileName = idlFile;
            IdlModule = idlModule;
        }
    }
}
