using System;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using CycloneDDS.Schema;

namespace CycloneDDS.CodeGen
{
    public class DeserializerEmitter
    {
        private HashSet<string> _generatedRefStructs = new HashSet<string>();
        private GlobalTypeRegistry? _registry;

        public string EmitDeserializer(TypeInfo type, GlobalTypeRegistry registry, bool generateUsings = true)
        {
            _registry = registry;
            var sb = new StringBuilder();
            sb.AppendLine("// CodeGen Version: DEBUG-CHECK-1");
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#pragma warning disable CS0162, CS0219, CS8600, CS8601, CS8602, CS8603, CS8604, CS8605, CS8618, CS8625");
            
            if (generateUsings)
            {
                sb.AppendLine("using CycloneDDS.Core;");
                sb.AppendLine("using System.Runtime.InteropServices;");
                sb.AppendLine("using System.Text;");
                sb.AppendLine("using System.Linq;");
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine();
            }
            
            if (!string.IsNullOrEmpty(type.Namespace))
            {
                sb.AppendLine($"namespace {type.Namespace}");
                sb.AppendLine("{");
            }
            
            EmitPartialStruct(sb, type);
            // EmitViewStruct(sb, type); // View not used for simple structs in this binding mode
            
            if (!string.IsNullOrEmpty(type.Namespace))
            {
                sb.AppendLine("}");
            }
            
            return sb.ToString();
        }
        
        private void EmitPartialStruct(StringBuilder sb, TypeInfo type)
        {
            string typeKind = type.IsClass ? "class" : "struct";
            sb.AppendLine($"    public partial {typeKind} {type.Name}");
            sb.AppendLine("    {");
            sb.AppendLine("         // Legacy CDR deserializer removed.");
            sb.AppendLine("    }");
        }
    }
}
