// <auto-generated>
// Generated from Resources/AdvancedTypes.idl for runtime tests.
// </auto-generated>

using System.Collections.Generic;
using CycloneDDS.Schema;

namespace AdvancedTypes
{
    public enum AdvancedTypes_DiscriminatorEnum : int
    {
        AdvancedtypesDiscOne = 0,
        AdvancedtypesDiscTwo = 1,
        AdvancedtypesDiscThree = 2
    }

    [DdsUnion]
    public partial struct IntUnion
    {
        [DdsDiscriminator]
        public int Discriminator;

        [DdsCase(1)]
        public int LongValue;

        [DdsCase(2)]
        [DdsManaged]
        public string StringValue;

        [DdsDefaultCase]
        public bool BoolValue;
    }

    [DdsUnion]
    public partial struct BoolUnion
    {
        [DdsDiscriminator]
        public bool Discriminator;

        [DdsCase(true)]
        public double DoubleValue;

        [DdsCase(false)]
        public int LongValue;
    }

    [DdsUnion]
    public partial struct EnumUnion
    {
        [DdsDiscriminator]
        public AdvancedTypes_DiscriminatorEnum Discriminator;

        [DdsCase(AdvancedTypes_DiscriminatorEnum.AdvancedtypesDiscOne)]
        public float FloatValue;

        [DdsCase(AdvancedTypes_DiscriminatorEnum.AdvancedtypesDiscTwo)]
        [DdsManaged]
        [MaxLength(32)]
        public string SmallString;

        [DdsDefaultCase]
        [DdsManaged]
        public List<byte> BytesValue;
    }

    [DdsStruct]
    public partial struct InnerInnerStruct
    {
        public int Id;

        [DdsManaged]
        public string Message;
    }

    [DdsStruct]
    public partial struct InnerStruct
    {
        public InnerInnerStruct DeepStruct;

        [DdsManaged]
        public List<double> Numbers;
    }

    [DdsStruct]
    public partial struct NestedStruct
    {
        public InnerStruct Inner;
        public int Level;
    }

    [DdsStruct]
    public partial struct OptionalStruct
    {
        public int MandatoryVal;
    }

    [DdsStruct]
    public partial struct OptionalInner
    {
        public int OptInt;
    }

    [DdsStruct]
    [DdsManaged]
    public partial struct AdvancedTypes_LongSeq
    {
        [DdsManaged]
        public List<int> Values;
    }

    [DdsStruct]
    public partial struct ComplexStruct
    {
        [DdsManaged]
        public List<AdvancedTypes_LongSeq> Matrix;

        [DdsManaged]
        [MaxLength(32)]
        public string FixedString;

        [DdsManaged]
        [MaxLength(10)]
        public List<int> BoundedSeq;

        [DdsOptional]
        public int? OptLong;

        [DdsOptional]
        public NestedStruct? OptStruct;
    }

    [DdsStruct]
    public partial struct AllTypes
    {
        public ComplexStruct Complex;
        public IntUnion UInt;
        public BoolUnion UBool;
        public EnumUnion UEnum;
        public NestedStruct Nested;
    }
}
