// <auto-generated>
// This file was generated by CycloneDDS.IdlImporter
// Original IDL: common_types.idl
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using CycloneDDS.Schema;

namespace CommonLib
{
    public enum Color : int
    {
        Red = 0,
        Green = 1,
        Blue = 2
    }

    [DdsStruct]
    [DdsExtensibility(DdsExtensibilityKind.Final)]
    public partial struct Point
    {
        public int X;
        public int Y;
    }

}

