// <auto-generated>
// This file was generated by CycloneDDS.IdlImporter
// Original IDL: common_types.idl
// Generation Date: 2026-02-17 18:06:51 UTC
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using CycloneDDS.Schema;

public enum CommonLib_Color : int
{
    CommonlibRed = 0,
    CommonlibGreen = 1,
    CommonlibBlue = 2
}

namespace CommonLib
{
    [DdsStruct]
    [DdsExtensibility(DdsExtensibilityKind.Final)]
    public partial struct Point
    {
        public int X;
        public int Y;
    }

}

