// <auto-generated />
using CycloneDDS.Schema;
using System.Reflection;

[assembly: DdsIdlMapping("Probe.MyUnion", "UnionProbe", "Probe")]
[assembly: DdsIdlMapping("Probe.UnionProbeStruct", "UnionProbe", "Probe")]
