// <auto-generated />
#pragma warning disable CS0162, CS0219, CS8600, CS8601, CS8602, CS8603, CS8604, CS8605, CS8618, CS8625
using System;
using CycloneDDS.Runtime;

namespace Probe
{
    public partial struct UnionProbeStruct
    {
        private static readonly uint[] _ops = new uint[] { 16973828, 0, 17629184, 4, 196614, 16973828, 12, 0, 67108864, 17367304, 0, 1, 524292, 134283264, 0, 4, 0, 0 };
        public static uint[] GetDescriptorOps() => _ops;
        public static DdsKeyDescriptor[] GetKeyDescriptors() => null;

        public static uint GetDescriptorFlagset() => 0;
        public static uint GetDescriptorSize() => 16;
        public static uint GetDescriptorAlign() => 4;
    }
}
