// <auto-generated />
#pragma warning disable CS0162, CS0219, CS8600, CS8601, CS8602, CS8603, CS8604, CS8605, CS8618, CS8625
using System;
using CycloneDDS.Core;
using CycloneDDS.Runtime;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Text;

namespace Probe
{
    public partial struct UnionProbeStruct
    {
        public static int GetNativeSize(in UnionProbeStruct source)
        {
            int size = Unsafe.SizeOf<UnionProbeStruct_Native>();
            size += GetDynamicSize(source);
            return size;
        }
        public static int GetNativeHeadSize()
        {
            return Unsafe.SizeOf<UnionProbeStruct_Native>();
        }

        private static int GetDynamicSize(in UnionProbeStruct source)
        {
            int currentOffset = Unsafe.SizeOf<UnionProbeStruct_Native>();
            int startOffset = currentOffset;
            var __U_dyn = Probe.MyUnion.GetNativeSize(source.U) - Unsafe.SizeOf<Probe.MyUnion_Native>();
            if (__U_dyn > 0)
            {
                currentOffset = (currentOffset + 7) & ~7;
                currentOffset += __U_dyn;
            }
            return currentOffset - startOffset;
        }
        public static unsafe void MarshalToNative(in UnionProbeStruct source, IntPtr targetPtr, ref NativeArena arena)
        {
            ref var target = ref Unsafe.AsRef<UnionProbeStruct_Native>((void*)targetPtr);
            target = default;
            MarshalToNative(source, ref target, ref arena);
        }

        internal static unsafe void MarshalToNative(in UnionProbeStruct source, ref UnionProbeStruct_Native target, ref NativeArena arena)
        {
            target.P1 = source.P1;
            var __U_temp = source.U;
            Probe.MyUnion.MarshalToNative(in __U_temp, ref target.U, ref arena);
            target.P2 = source.P2;
        }

        internal static unsafe void MarshalFromNative(IntPtr nativeData, out UnionProbeStruct managedData)
        {
            managedData = default;
            MarshalFromNative(ref managedData, in System.Runtime.CompilerServices.Unsafe.AsRef<UnionProbeStruct_Native>((void*)nativeData));
        }

        internal static unsafe void MarshalFromNative(ref UnionProbeStruct target, in UnionProbeStruct_Native source)
        {
            System.Console.WriteLine("MarshalFromNative UnionProbeStruct");
            target.P1 = source.P1;
            var __U_target = new Probe.MyUnion();
            Probe.MyUnion.MarshalFromNative(ref __U_target, in source.U);
            target.U = __U_target;
            target.P2 = source.P2;
        }

        public static unsafe UnionProbeStruct FromNative(IntPtr nativePtr)
        {
            if (nativePtr == IntPtr.Zero) return default;
            var native = *(UnionProbeStruct_Native*)nativePtr;
            var managed = new UnionProbeStruct();
            MarshalFromNative(ref managed, in native);
            return managed;
        }

    }
    /// <summary>
    /// Native C-compatible struct for UnionProbeStruct.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal struct UnionProbeStruct_Native
    {
        public System.Int32 P1;
        public Probe.MyUnion_Native U;
        public System.Int32 P2;
    }
}
