module Probe {
    union MyUnion switch(boolean) {
        case TRUE: octet ValA;
        case FALSE: octet ValB;
    };
    union DoubleUnion switch(boolean) {
        case TRUE: double DVal;
        case FALSE: long LVal;
    };
    struct UnionProbeStruct {
        long P1;            // Marker 0xAAAA
        MyUnion U;          // Target
        long P2;            // Marker 0xBBBB
    };
    struct DoubleUnionProbeStruct {
        long P1;
        DoubleUnion U;
        long P2;
    };
};
