/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: UnionProbe.h
  Source: D:\Work\FastCycloneDdsCsharpBindings\tests\UnionProbe\UnionProbe.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_UNIONPROBE_H_8D36C57045E95A1480173C07B5CF9B72
#define DDSC_UNIONPROBE_H_8D36C57045E95A1480173C07B5CF9B72

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Probe_MyUnion
{
  bool _d;
  union
  {
    uint8_t ValA;
    uint8_t ValB;
  } _u;
} Probe_MyUnion;

extern const dds_topic_descriptor_t Probe_MyUnion_desc;

#define Probe_MyUnion__alloc() \
((Probe_MyUnion*) dds_alloc (sizeof (Probe_MyUnion)));

#define Probe_MyUnion_free(d,o) \
dds_sample_free ((d), &Probe_MyUnion_desc, (o))

typedef struct Probe_DoubleUnion
{
  bool _d;
  union
  {
    double DVal;
    int32_t LVal;
  } _u;
} Probe_DoubleUnion;

extern const dds_topic_descriptor_t Probe_DoubleUnion_desc;

#define Probe_DoubleUnion__alloc() \
((Probe_DoubleUnion*) dds_alloc (sizeof (Probe_DoubleUnion)));

#define Probe_DoubleUnion_free(d,o) \
dds_sample_free ((d), &Probe_DoubleUnion_desc, (o))

typedef struct Probe_UnionProbeStruct
{
  int32_t P1;
  struct Probe_MyUnion U;
  int32_t P2;
} Probe_UnionProbeStruct;

extern const dds_topic_descriptor_t Probe_UnionProbeStruct_desc;

#define Probe_UnionProbeStruct__alloc() \
((Probe_UnionProbeStruct*) dds_alloc (sizeof (Probe_UnionProbeStruct)));

#define Probe_UnionProbeStruct_free(d,o) \
dds_sample_free ((d), &Probe_UnionProbeStruct_desc, (o))

typedef struct Probe_DoubleUnionProbeStruct
{
  int32_t P1;
  struct Probe_DoubleUnion U;
  int32_t P2;
} Probe_DoubleUnionProbeStruct;

extern const dds_topic_descriptor_t Probe_DoubleUnionProbeStruct_desc;

#define Probe_DoubleUnionProbeStruct__alloc() \
((Probe_DoubleUnionProbeStruct*) dds_alloc (sizeof (Probe_DoubleUnionProbeStruct)));

#define Probe_DoubleUnionProbeStruct_free(d,o) \
dds_sample_free ((d), &Probe_DoubleUnionProbeStruct_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_UNIONPROBE_H_8D36C57045E95A1480173C07B5CF9B72 */
