/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: D:\Work\FastCycloneDdsCsharpBindings\tests\GoldenRig_Union/UnionTest.h
  Source: D:\Work\FastCycloneDdsCsharpBindings\tests\GoldenRig_Union\UnionTest.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_GOLDENRIG_UNION_UNIONTEST_H
#define DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_GOLDENRIG_UNION_UNIONTEST_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct TestUnion
{
  int32_t _d;
  union
  {
    int32_t valueA;
    double valueB;
  } _u;
} TestUnion;

extern const dds_topic_descriptor_t TestUnion_desc;

#define TestUnion__alloc() \
((TestUnion*) dds_alloc (sizeof (TestUnion)));

#define TestUnion_free(d,o) \
dds_sample_free ((d), &TestUnion_desc, (o))

typedef struct Container
{
  struct TestUnion u;
} Container;

extern const dds_topic_descriptor_t Container_desc;

#define Container__alloc() \
((Container*) dds_alloc (sizeof (Container)));

#define Container_free(d,o) \
dds_sample_free ((d), &Container_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_GOLDENRIG_UNION_UNIONTEST_H */
