// <auto-generated />
using CycloneDDS.Schema;
using System.Reflection;

[assembly: DdsIdlMapping("CycloneDDS.Runtime.Tests.KeyedMessages.SingleKeyMessage", "SingleKeyMessage", "CycloneDDS::Runtime::Tests::KeyedMessages")]
