using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using Xunit;
using Xunit.Abstractions;
using CycloneDDS.Core;
using AdvancedTypes;
using System.Reflection;

namespace CycloneDDS.Runtime.Tests
{
    public class OffsetDebug
    {
        private readonly ITestOutputHelper _output;

        public OffsetDebug(ITestOutputHelper output)
        {
            _output = output;
        }

        [Fact]
        public void PrintOffsets()
        {
            Console.WriteLine($"DdsSequenceNative Size: {Unsafe.SizeOf<DdsSequenceNative>()}");
            Console.WriteLine($"IntPtr Size: {IntPtr.Size}");
            Console.WriteLine("DdsSequenceNative Fields:");
            foreach (var field in typeof(DdsSequenceNative).GetFields())
            {
                var offset = Marshal.OffsetOf(typeof(DdsSequenceNative), field.Name);
                Console.WriteLine($"  {field.Name}: {offset}");
            }

            // Get ComplexStruct_Native
            // It is likely an internal nested type or sibling type generated by source generator.
            // Since I cannot access it easily if it's internal and not IVT, I'll rely on DdsSequenceNative for now.
            // But wait, the generated code for serializer is internal.
            
            // However, "AdvancedTypes" is the namespace.
            // The Native structs might be public or internal?
            // Usually internal.
            
            // Let's try to find it via reflection from the assembly containing AllTypes.
            var assembly = typeof(AdvancedTypes.AllTypes).Assembly;
            var nativeType = assembly.GetType("AdvancedTypes.ComplexStruct_Native");
            
            if (nativeType != null)
            {
                Console.WriteLine($"ComplexStruct_Native Size: {Marshal.SizeOf(nativeType)}"); // Marshal.SizeOf for sturcts
                foreach (var field in nativeType.GetFields())
                {
                    var offset = Marshal.OffsetOf(nativeType, field.Name);
                    Console.WriteLine($"  {field.Name}: {offset}");
                }
            }
            else
            {
                Console.WriteLine("Could not find ComplexStruct_Native via reflection.");
            }
        }
    }
}
