/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: d:\Work\FastCycloneDdsCsharpBindings\tests\CycloneDDS.Runtime.Tests\KeyedMessages\temp_c/CompositeKeyMessage.h
  Source: D:\Work\FastCycloneDdsCsharpBindings\tests\CycloneDDS.Runtime.Tests\KeyedMessages\CompositeKeyMessage.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_COMPOSITEKEYMESSAGE_H_2DA1CC1563724755DD5FB8AC3054682F
#define DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_COMPOSITEKEYMESSAGE_H_2DA1CC1563724755DD5FB8AC3054682F

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CycloneDDS_Runtime_Tests_KeyedMessages_CompositeKeyMessage
{
  int32_t sensorId;
  int32_t locationId;
  double temperature;
} CycloneDDS_Runtime_Tests_KeyedMessages_CompositeKeyMessage;

extern const dds_topic_descriptor_t CycloneDDS_Runtime_Tests_KeyedMessages_CompositeKeyMessage_desc;

#define CycloneDDS_Runtime_Tests_KeyedMessages_CompositeKeyMessage__alloc() \
((CycloneDDS_Runtime_Tests_KeyedMessages_CompositeKeyMessage*) dds_alloc (sizeof (CycloneDDS_Runtime_Tests_KeyedMessages_CompositeKeyMessage)));

#define CycloneDDS_Runtime_Tests_KeyedMessages_CompositeKeyMessage_free(d,o) \
dds_sample_free ((d), &CycloneDDS_Runtime_Tests_KeyedMessages_CompositeKeyMessage_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_COMPOSITEKEYMESSAGE_H_2DA1CC1563724755DD5FB8AC3054682F */
