/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: d:\Work\FastCycloneDdsCsharpBindings\tests\CycloneDDS.Runtime.Tests\KeyedMessages\temp_c/NestedKeyMessage.h
  Source: D:\Work\FastCycloneDdsCsharpBindings\tests\CycloneDDS.Runtime.Tests\KeyedMessages\NestedKeyMessage.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_NESTEDKEYMESSAGE_H_AEFB30DBAAA317102F11B08A4FA7D5CB
#define DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_NESTEDKEYMESSAGE_H_AEFB30DBAAA317102F11B08A4FA7D5CB

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CycloneDDS_Runtime_Tests_KeyedMessages_NestedKeyMessage
{
  int32_t innerId;
  char * data;
} CycloneDDS_Runtime_Tests_KeyedMessages_NestedKeyMessage;

extern const dds_topic_descriptor_t CycloneDDS_Runtime_Tests_KeyedMessages_NestedKeyMessage_desc;

#define CycloneDDS_Runtime_Tests_KeyedMessages_NestedKeyMessage__alloc() \
((CycloneDDS_Runtime_Tests_KeyedMessages_NestedKeyMessage*) dds_alloc (sizeof (CycloneDDS_Runtime_Tests_KeyedMessages_NestedKeyMessage)));

#define CycloneDDS_Runtime_Tests_KeyedMessages_NestedKeyMessage_free(d,o) \
dds_sample_free ((d), &CycloneDDS_Runtime_Tests_KeyedMessages_NestedKeyMessage_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_NESTEDKEYMESSAGE_H_AEFB30DBAAA317102F11B08A4FA7D5CB */
