/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: d:\Work\FastCycloneDdsCsharpBindings\tests\CycloneDDS.Runtime.Tests\KeyedMessages\temp_c/SingleKeyMessage.h
  Source: D:\Work\FastCycloneDdsCsharpBindings\tests\CycloneDDS.Runtime.Tests\KeyedMessages\SingleKeyMessage.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_SINGLEKEYMESSAGE_H_C04E97231F1372AB85B8334B22FBB1D8
#define DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_SINGLEKEYMESSAGE_H_C04E97231F1372AB85B8334B22FBB1D8

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CycloneDDS_Runtime_Tests_KeyedMessages_SingleKeyMessage
{
  int32_t deviceId;
  int32_t value;
  int64_t timestamp;
} CycloneDDS_Runtime_Tests_KeyedMessages_SingleKeyMessage;

extern const dds_topic_descriptor_t CycloneDDS_Runtime_Tests_KeyedMessages_SingleKeyMessage_desc;

#define CycloneDDS_Runtime_Tests_KeyedMessages_SingleKeyMessage__alloc() \
((CycloneDDS_Runtime_Tests_KeyedMessages_SingleKeyMessage*) dds_alloc (sizeof (CycloneDDS_Runtime_Tests_KeyedMessages_SingleKeyMessage)));

#define CycloneDDS_Runtime_Tests_KeyedMessages_SingleKeyMessage_free(d,o) \
dds_sample_free ((d), &CycloneDDS_Runtime_Tests_KeyedMessages_SingleKeyMessage_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_SINGLEKEYMESSAGE_H_C04E97231F1372AB85B8334B22FBB1D8 */
