/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: d:\Work\FastCycloneDdsCsharpBindings\tests\CycloneDDS.Runtime.Tests\KeyedMessages\temp_c/StringMessage.h
  Source: D:\Work\FastCycloneDdsCsharpBindings\tests\CycloneDDS.Runtime.Tests\KeyedMessages\StringMessage.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_STRINGMESSAGE_H_EC481436787D90B83043ECF69ABCB884
#define DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_STRINGMESSAGE_H_EC481436787D90B83043ECF69ABCB884

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CycloneDDS_Runtime_Tests_StringMessage
{
  int32_t id;
  char * msg;
} CycloneDDS_Runtime_Tests_StringMessage;

extern const dds_topic_descriptor_t CycloneDDS_Runtime_Tests_StringMessage_desc;

#define CycloneDDS_Runtime_Tests_StringMessage__alloc() \
((CycloneDDS_Runtime_Tests_StringMessage*) dds_alloc (sizeof (CycloneDDS_Runtime_Tests_StringMessage)));

#define CycloneDDS_Runtime_Tests_StringMessage_free(d,o) \
dds_sample_free ((d), &CycloneDDS_Runtime_Tests_StringMessage_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_STRINGMESSAGE_H_EC481436787D90B83043ECF69ABCB884 */
