/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: d:\Work\FastCycloneDdsCsharpBindings\tests\CycloneDDS.Runtime.Tests\KeyedMessages\temp_c/TestMessage.h
  Source: D:\Work\FastCycloneDdsCsharpBindings\tests\CycloneDDS.Runtime.Tests\KeyedMessages\TestMessage.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_TESTMESSAGE_H_6746A90D530668C64F73259944F8350F
#define DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_TESTMESSAGE_H_6746A90D530668C64F73259944F8350F

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CycloneDDS_Runtime_Tests_TestMessage
{
  int32_t id;
  int32_t value;
} CycloneDDS_Runtime_Tests_TestMessage;

extern const dds_topic_descriptor_t CycloneDDS_Runtime_Tests_TestMessage_desc;

#define CycloneDDS_Runtime_Tests_TestMessage__alloc() \
((CycloneDDS_Runtime_Tests_TestMessage*) dds_alloc (sizeof (CycloneDDS_Runtime_Tests_TestMessage)));

#define CycloneDDS_Runtime_Tests_TestMessage_free(d,o) \
dds_sample_free ((d), &CycloneDDS_Runtime_Tests_TestMessage_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_CYCLONEDDS_RUNTIME_TESTS_KEYEDMESSAGES_TEMP_C_TESTMESSAGE_H_6746A90D530668C64F73259944F8350F */
