using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using CycloneDDS.Compiler.Common.IdlJson;

namespace CycloneDDS.IdlImporter;

public class CSharpEmitter
{
    private readonly TypeMapper _typeMapper;

    public CSharpEmitter(TypeMapper typeMapper)
    {
        _typeMapper = typeMapper;
    }

    public void GenerateCSharp(List<JsonTypeDefinition> types, string originalIdlFileName, string outputFilePath)
    {
        var sb = new StringBuilder();
        
        // Header
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file was generated by CycloneDDS.IdlImporter");
        sb.AppendLine($"// Original IDL: {originalIdlFileName}");
        sb.AppendLine($"// Generation Date: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using CycloneDDS.Schema;");
        sb.AppendLine();

        // Group by namespace
        var typesByNamespace = types
            .GroupBy(t => GetNamespaceFromType(t.Name))
            .OrderBy(g => g.Key);

        foreach (var group in typesByNamespace)
        {
            var ns = group.Key;
            bool hasNamespace = !string.IsNullOrEmpty(ns);

            if (hasNamespace)
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }
            
            foreach (var type in group)
            {
                EmitType(sb, type, hasNamespace ? 1 : 0);
            }

            if (hasNamespace)
            {
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }
        
        File.WriteAllText(outputFilePath, sb.ToString());
    }

    private string GetNamespaceFromType(string fullTypeName)
    {
        string csName = _typeMapper.GetCSharpNamespace(fullTypeName);
        int lastDot = csName.LastIndexOf('.');
        if (lastDot > 0)
        {
            return csName.Substring(0, lastDot);
        }
        return string.Empty; // Global namespace
    }

    private string GetSimpleTypeName(string fullTypeName)
    {
        string csName = _typeMapper.GetCSharpNamespace(fullTypeName);
        int lastDot = csName.LastIndexOf('.');
        if (lastDot >= 0)
        {
            return csName.Substring(lastDot + 1);
        }
        return csName;
    }

    private void EmitType(StringBuilder sb, JsonTypeDefinition type, int indentLevel)
    {
        string indent = new string(' ', indentLevel * 4);
        string typeName = GetSimpleTypeName(type.Name);
        
        if (type.Kind == "struct")
        {
            EmitStruct(sb, type, typeName, indent);
        }
        else if (type.Kind == "enum")
        {
            EmitEnum(sb, type, typeName, indent);
        }
    }

    private void EmitStruct(StringBuilder sb, JsonTypeDefinition type, string typeName, string indent)
    {
        bool hasIdsKey = type.Members.Any(m => m.IsKey);
        
        if (hasIdsKey)
        {
             sb.AppendLine($"{indent}[DdsTopic(\"{type.Name}\")]"); 
        }
        else
        {
             sb.AppendLine($"{indent}[DdsStruct(\"{type.Name}\")]");
        }
        
        if (!string.IsNullOrEmpty(type.Extensibility))
        {
            string kind = type.Extensibility.ToLower() switch 
            {
                "final" => "Final",
                "appendable" => "Appendable",
                "mutable" => "Mutable",
                _ => "Final"
            };
            sb.AppendLine($"{indent}[DdsExtensibility(DdsExtensibilityKind.{kind})]");
        }

        sb.AppendLine($"{indent}public partial struct {typeName}");
        sb.AppendLine($"{indent}{{");
        
        foreach (var member in type.Members)
        {
            EmitStructMember(sb, member, indent + "    ");
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private void EmitStructMember(StringBuilder sb, JsonMember member, string indent)
    {
        var (csType, isManaged, arrayLen, bound) = _typeMapper.MapMember(member);
        
        if (member.IsKey) sb.AppendLine($"{indent}[DdsKey]");
        
        if (csType == "string" && bound > 0)
        {
            sb.AppendLine($"{indent}[DdsString({bound})]");
        }
        
        sb.AppendLine($"{indent}public {csType} {ToPascalCase(member.Name)};");
    }

    private void EmitEnum(StringBuilder sb, JsonTypeDefinition type, string typeName, string indent)
    {
        sb.AppendLine($"{indent}public enum {typeName} : int");
        sb.AppendLine($"{indent}{{");
        
        for (int i = 0; i < type.Members.Count; i++)
        {
            var m = type.Members[i];
            string comma = (i < type.Members.Count - 1) ? "," : "";
            int val = m.Value ?? (m.Id ?? i);
            sb.AppendLine($"{indent}    {ToPascalCase(m.Name)} = {val}{comma}");
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        if (name == "_d") return "_d";

        var parts = name.Split('_', StringSplitOptions.RemoveEmptyEntries);
        var sb = new StringBuilder();
        
        foreach (var part in parts)
        {
            if (part.Length > 0)
            {
                sb.Append(char.ToUpper(part[0]));
                if (part.Length > 1)
                {
                    sb.Append(part.Substring(1).ToLower());
                }
            }
        }
        
        return sb.ToString();
    }
}
