// <auto-generated>
// This file was generated by CycloneDDS.IdlImporter
// Original IDL: app_types.idl
// Generation Date: 2026-02-17 18:28:09 UTC
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using CycloneDDS.Schema;

namespace AppLib
{
    [DdsUnion]
    public partial struct Result
    {
        [DdsDiscriminator]
        public bool _d;
        [DdsCase(1)]
        public CommonLib.Point Value;
        [DdsCase(0)]
        [DdsManaged]
        public string Msg;
    }

    [DdsTopic("AppLib::ExtendedPoint")]
    [DdsExtensibility(DdsExtensibilityKind.Final)]
    public partial struct ExtendedPoint
    {
        [DdsKey]
        public int Id;
        public CommonLib.Point BasePoint;
        public CommonLib.Color Color;
        public AppLib.Result ExtraInfo;
        [DdsManaged]
        public List<string> Tags;
    }

}

