// <auto-generated>
// This file was generated by CycloneDDS.IdlImporter
// Original IDL: app_types.idl
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using CycloneDDS.Schema;

namespace AppLib
{
    [DdsUnion]
    public partial struct Result
    {
        [DdsDiscriminator]
        public bool _d;
        [DdsCase(1)]
        public CommonLib.Point value;
        [DdsCase(0)]
        [DdsManaged]
        public string msg;
    }

    [DdsTopic("AppLib::ExtendedPoint")]
    [DdsExtensibility(DdsExtensibilityKind.Final)]
    public partial struct ExtendedPoint
    {
        [DdsKey]
        public int id;
        public CommonLib.Point base_point;
        public CommonLib.Color color;
        public AppLib.Result extra_info;
        [DdsManaged]
        public List<string> tags;
    }

}

