// <auto-generated>
// Generated for layout probe tests.
// </auto-generated>

using System.Collections.Generic;
using CycloneDDS.Schema;

namespace Probe
{
    [DdsStruct]
    public partial struct SequenceProbe
    {
        public int P1;

        [DdsManaged]
        public List<int> Seq;

        public int P2;
    }
}
